.PHONY: next-build next-test next-run next-serve

next-build:
	cargo build --workspace

next-test:
	cargo test --workspace

next-run:
	cargo run -p rsetup-next -- --demo tui

next-serve:
	cargo run -p rsetup-next -- --demo serve
