[package]
name = "rsetup-desktop"
version = "0.5.0-alpha.1"
edition = "2024"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rsetup-core = { path = "../../../crates/rsetup-core" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
