#!/bin/sh
set -eu

rsetup-next --demo status --json | grep -q '"identity"'
rsetup-next --demo actions --json | grep -q '"system.update"'
test -x /usr/libexec/rsetup-next-helper
test -f /usr/share/polkit-1/actions/com.radxa.rsetup-next.policy
